name: mantra_biometric
description: Mantra biometric plugin is to enable the biometric based aadhaar authentication with registered device concept implemented by UIDAI.
version: 0.0.3
homepage: https://github.com/Ajaykamble/mantra_biometric_plugin.git

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.17.0
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  xml: ^6.5.0
  js: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  plugin:
    platforms:
      android:
        package: com.ajaykamble.mantra_biometric
        pluginClass: MantraBiometricPlugin
      web:
        pluginClass: MantraBiometricWeb
        fileName: mantra_biometric_web.dart
      windows:
        pluginClass: MantraBiometricPlugin
  assets:
    - assets/mantra.js

