name: mantra_biometric
description: Mantra biometric plugin is to enable the biometric based aadhaar authentication with registered device concept implemented by UIDAI.
version: 0.0.2
homepage: https://github.com/Ajaykamble/mantra_biometric_plugin.git

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  xml: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ajaykamble.mantra_biometric
        pluginClass: MantraBiometricPlugin

